name: Generate Snake Animation

on:
  schedule: # Run automaticamente a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: Artur-Antunes-1
          output: dist/snake.svg

      - name: Push the SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_files: true
